 # This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: PythonDemo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  #Allows you to run this workflow manually from the actions tab
  workflow_dispatch:
      

jobs:
  # This workflow contains a single job called buid
  build:

    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        # optional - x64 or x86 architecture, defaults to x64
    #Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
    # Install and test with pytest
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pytest test.py